### ISSUE TITLE
Unsatisfiable requirements detected for package PolynomialZeros

### ISSUE THREAD

**Issue by jarlebring** [jverzani/PolynomialZeros.jl#12]
Thanks for great work in this package. We started experiencing problems with dependencies with PolynomialZeros a couple of days ago, both in julia 0.7 and 1.0. 
```
(NonlinearEigenproblems) pkg> add PolynomialZeros
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package PolynomialZeros [11d3f387]:
 PolynomialZeros [11d3f387] log:
 ├─possible versions are: [0.0.1, 0.1.0] or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions [0.0.1, 0.1.0]
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left
(NonlinearEigenproblems) pkg> status
Project NonlinearEigenproblems v0.1.0
    Status `Project.toml`
  [7d9fca2a] Arpack v0.2.3
  [7a1cc6ca] FFTW v0.2.4
  [42fd0dbc] IterativeSolvers v0.7.1
  [7a12625a] LinearMaps v2.2.0
  [3a141323] PolynomialRoots v0.2.0
  [f27b6e38] Polynomials v0.5.0
  [276daf66] SpecialFunctions v0.7.0
  [a759f4b9] TimerOutputs v0.4.0
  [8ba89e20] Distributed 
  [b77e0a4c] InteractiveUtils 
  [37e2e46d] LinearAlgebra 
  [de0858da] Printf 
  [9a3f8284] Random 
  [2f01184e] SparseArrays 
  [10745b16] Statistics 
  [4607b0f0] SuiteSparse 
  [8dfed614] Test 
```
Any ideas where the issue stems from? Apologies in advance if the problem does not stem from this package.

**Comment by jarlebring** [comment]
Maybe it has something to do with this commit in JuliaRegistry. https://github.com/JuliaRegistries/General/commit/242d6bd8d6e09890418d4a8df4eeab88c55579e3#diff-775b996938a879743a87fa45f0e80e73   It seems it changed to only supporting julia 0.6?

**Comment by jverzani** [comment]
Yeah, sorry. That was necessary for another package. And the released one supports1.0 onward due to another. If you have to be on 0.7 you will need to pin to an old release, I think.

**Comment by jarlebring** [comment]
I get the same error message on julia 1.0. Maybe I misunderstood you. Shouldn't there be a PolynomialZeros v0.2.0 also in the julia registry https://github.com/JuliaRegistries/General/blob/242d6bd8d6e09890418d4a8df4eeab88c55579e3/P/PolynomialZeros/Versions.toml? 

As far as I understand, pinning means fixing to the current version. This does not seem possible if you cannot install the package in the first place. Maybe it is possible to hack by editing Project.toml, but our package has a dependency on PolynomialZeros, and we don't want to ask the user to do that. 

Any thoughts on if/when this can be resolved?

**Comment by jverzani** [comment]
Yes, there are oddities.

I can get most of the tests working on v0.7.0 with this

```
] add PolynomialZeros#12379a86096d2aa433fe40484f181529f17610b6
```

But some of the tests over the rationals fail.

On v1.0, I thought the tagged release was working, but now I'm not so sure. I `free`d the package, then `rm`ed it, then tried to `add` it and am getting `ERROR: Git repository not found at 'PolynomialZeros'`.

I'll see what I can do to dig into this. Sorry for the trouble.

**Comment by jverzani** [comment]
Okay, I had tagged a release, but it never worked its way through METADATA. (There was some issue with IntervalArithmetic). Hopefully that is addressed. I've just put in a PR to tag v0.2.0 (again). With luck this will help you use the package, though only within v1.0 forward.

**Comment by jarlebring** [comment]
Thanks for the quick actions. Our package will soon only support julia 1.0 anyway.

**Comment by jverzani** [comment]
Great. What part of PolynomialZeros do you end up using? Maybe you don't need the full dependency.

**Comment by jarlebring** [comment]
The main usage is accurate roots of a polynomial with Float64 coefficients, but we support also other types BigFloat, etc.

**Comment by jarlebring** [comment]
PolynomialZeros now works on julia v1.0, which is fine for us. Thanks! If you want to know how we use it check out:  https://github.com/nep-pack/NonlinearEigenproblems.jl
